services:
  - type: worker
    name: celery-worker
    region: oregon
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "celery --app SummarizeAI worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: redis://red-cqh7a45svqrc73cbgr30:6379
        fromService:
          name: summarizeai-redis
          type: redis
          property: connectionString
  - type: web
    plan: free
    name: SummarizeAI
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn SummarizeAI.asgi:application -k uvicorn.workers.UvicornWorker"