# Generated by Django 5.0.7 on 2024-07-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='space',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webpagesummary',
            name='summary_ptr',
        ),
        migrations.DeleteModel(
            name='YoutubeVideoSummary',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='WebPageSummary',
        ),
    ]
