# Generated by Django 5.0.7 on 2024-07-16 18:19

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_remove_summary_space_remove_summary_user_and_more'),
        ('dashboard', '0002_alter_space_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('vectorstore', models.JSONField(blank=True, null=True)),
                ('question_answers', models.JSONField(blank=True, null=True)),
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPageSummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.summary')),
                ('link', models.TextField()),
            ],
            bases=('api.summary',),
        ),
        migrations.CreateModel(
            name='YoutubeVideoSummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.summary')),
                ('video_id', models.CharField(max_length=100)),
            ],
            bases=('api.summary',),
        ),
    ]
