# Generated by Django 5.0.7 on 2024-07-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='space',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='vectorstore',
        ),
    ]
