# Generated by Django 5.0.7 on 2024-07-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_summary_space_remove_summary_vectorstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webpagesummary',
            name='summary_ptr',
        ),
        migrations.DeleteModel(
            name='YoutubeVideoSummary',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='WebPageSummary',
        ),
    ]
