# Generated by Django 5.0.7 on 2024-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpagesummary',
            name='vectorstore',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideosummary',
            name='vectorstore',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
