# Generated by Django 5.0.7 on 2024-07-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_webpagesummary_vectorstore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagesummary',
            name='vectorstore',
        ),
        migrations.RemoveField(
            model_name='youtubevideosummary',
            name='vectorstore',
        ),
    ]
