# Generated by Django 5.0.7 on 2024-07-24 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_webpagesummary_vectorstore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagesummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='youtubevideosummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
