# Generated by Django 5.0.7 on 2024-07-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={},
        ),
    ]
